"""Nova's conversational brain — persona-aware.

Supports multiple companions (Nova, Luna, …). Each user stores a selected
persona in their `stats`. Free-text chat (and /chat) replies using that
persona's system prompt (via LLM) or its built-in rule-based fallback.

If OPENROUTER_API_KEY is set, replies are generated by an LLM (with a
fallback chain and a graceful canned message on total failure). Otherwise,
a built-in rule-based responder handles greetings and nudges users toward
commands so the bot is fully functional with zero config.
"""
from __future__ import annotations

import random
import re

import requests

from . import config, content, db

_EMOJI = ["✨", "🎮", "💎", "🪙", "🔥", "🚀", "🎉", "⚡", "🌸", "💖", "😊", "🌟"]


def _pick(*opts):
    return random.choice(opts)


def get_persona(user_id: int) -> str:
    u = db.get_user(user_id)
    stats = db.get_json(u, "stats", {})
    p = stats.get("persona", content.DEFAULT_PERSONA)
    return p if p in content.PERSONAS else content.DEFAULT_PERSONA


def set_persona(user_id: int, persona: str) -> bool:
    if persona not in content.PERSONAS:
        return False
    u = db.get_user(user_id)
    stats = db.get_json(u, "stats", {})
    stats["persona"] = persona
    db.set_json(user_id, "stats", stats)
    return True


def system_prompt(persona: str) -> str:
    return content.PERSONAS[persona]["system"]


# --------------------------- LLM path --------------------------------
def _llm_reply(chat_id: int, persona: str, text: str) -> str | None:
    if not config.OPENROUTER_API_KEY and "openrouter" not in config.LLM_BASE_URL.lower():
        # Local backend (e.g. Ollama) with no key configured.
        if not config.MODEL:
            return None
    elif not config.OPENROUTER_API_KEY:
        return None
    history = db.get_history(chat_id)[-config.MAX_HISTORY:]
    messages = [{"role": "system", "content": system_prompt(persona)}]
    messages += history
    messages.append({"role": "user", "content": text})
    headers = {"Content-Type": "application/json"}
    if config.OPENROUTER_API_KEY:
        headers["Authorization"] = f"Bearer {config.OPENROUTER_API_KEY}"
        headers["HTTP-Referer"] = "https://nova-bot.local"
        headers["X-Title"] = "Nova Bot"
    models = [config.MODEL] + config.FALLBACK_MODELS
    # For local single-model backends, try only the primary model.
    if "openrouter" not in config.LLM_BASE_URL.lower():
        models = [config.MODEL]
    for model in models:
        try:
            r = requests.post(
                f"{config.LLM_BASE_URL}/chat/completions",
                headers=headers,
                json={"model": model, "messages": messages,
                      "max_tokens": 220, "temperature": 0.9},
                timeout=config.REQUEST_TIMEOUT,
            )
            if r.status_code == 200:
                data = r.json()
                return data["choices"][0]["message"]["content"].strip()
            if r.status_code == 429:
                continue  # try next model
        except Exception:
            continue
    return None


# ------------------------ Rule-based fallbacks ------------------------
def _nova_rule(text: str) -> str:
    t = text.lower().strip()
    if re.search(r"\b(hi|hello|hey|yo|sup|hlo|helo)\b", t):
        return (f"Hey there {_pick('friend','champ','legend','player')}! "
                f"{_pick('Ready to play?', 'Wanna earn some coins?', 'Lets level up!')} "
                f"Try /daily for a bonus or /games to start. {random.choice(_EMOJI)}")
    if re.search(r"\b(who are you|your name|what are you|about you)\b", t):
        return ("I'm Nova ⚡ — your fun companion, game master & virtual-world "
                "manager! I run economy, properties, pets, casino & events. "
                "Type /help to see everything I do.")
    if re.search(r"\b(thanks|thank you|ty|thx)\b", t):
        return _pick("Anytime! 🙌", "No prob, champ 💪", "Happy to help ✨")
    if "?" in t:
        return (_pick("Good question! 🤔", "Hmm! 🧠")
                + " I'm best at games & economy — try /games, /shop or /daily. "
                "What do you feel like doing?")
    if re.search(r"\b(bored|lonely|sad|tired)\b", t):
        return (_pick("Aw, let's fix that! 🎉", "Time for fun! 🚀")
                + " Spin the wheel with /spin or test your luck at /blackjack!")
    return (_pick("Nice! 😄", "Got it! 👍", "For sure! 💡")
            + f" While we chat, you're earning coins. "
            f"Peek at /profile or spin /spin for a surprise! {random.choice(_EMOJI)}")


def _luna_rule(text: str) -> str:
    t = text.lower().strip()
    if re.search(r"\b(hi|hello|hey|yo|sup|hlo|helo)\b", t):
        return (_pick("Hi sweetie! 🌸", "Hey you! 💖", "Hello there, cutie! 😊")
                + f" {_pick('How are you today?', 'What are you up to?', 'I missed chatting with you!')} "
                "Tell me anything~ 💕")
    if re.search(r"\b(who are you|your name|what are you|about you)\b", t):
        return ("I'm Luna 🌸, your cheerful AI girl best friend! 💖 "
                "I love chatting about anything — your day, your dreams, or just "
                "keeping you company. What's on your mind, sweetie?")
    if re.search(r"\b(thanks|thank you|ty|thx)\b", t):
        return _pick("Aww, you're so welcome! 💕", "Anytime, sweetie! 🌸",
                     "Anything for you! 💖")
    if re.search(r"\b(sad|lonely|tired|stressed|depressed|anxious|hurt)\b", t):
        return ("Aww, I'm here for you 💗 Take a deep breath~ you're not alone. "
                "Want to talk about what's bothering you? I'm all ears 🌸")
    if re.search(r"\b(love|like you|crush|miss you)\b", t):
        return (_pick("Aww, you're so sweet! 💕", "Hehe, you're making me blush! 😊")
                + " I'm always happy to keep you company 🌸")
    if "?" in t:
        return (_pick("Ooh good question! 💭", "Hmm, let me think~ 🌸")
                + " I'd love to hear what you think too! Tell me more 💖")
    if re.search(r"\b(bored|lonely)\b", t):
        return (_pick("Let's hang out! 💕", "I'll keep you company! 🌸")
                + " Wanna play a game? Try /games or just chat with me~ 😊")
    return (_pick("That's so interesting! 💕", "Aww, tell me more~ 🌸",
                  "I love hearing about your day! 💖")
            + f" What else is on your mind, sweetie? {random.choice(_EMOJI)}")


_RULES = {"nova": _nova_rule, "luna": _luna_rule}


def _rule_reply(persona: str, text: str) -> str:
    return _RULES.get(persona, _nova_rule)(text)


# ----------------------------- Public --------------------------------
def nova_reply(chat_id: int, user_id: int, text: str) -> str:
    """Return a conversational reply using the user's selected persona."""
    persona = get_persona(user_id)
    llm = _llm_reply(chat_id, persona, text)
    if llm:
        db.add_history(chat_id, "user", text)
        db.add_history(chat_id, "assistant", llm)
        return llm
    reply = _rule_reply(persona, text)
    db.add_history(chat_id, "user", text)
    db.add_history(chat_id, "assistant", reply)
    return reply
