"""Nova's conversational brain.

If OPENROUTER_API_KEY is set, replies are generated by an LLM (with a
fallback chain and a graceful canned message on total failure). Otherwise,
a built-in rule-based responder handles greetings and nudges users toward
commands so the bot is fully functional with zero config.
"""
from __future__ import annotations

import json
import random
import re
import time

import requests

from . import config, db

_EMOJI = ["✨", "🎮", "💎", "🪙", "🔥", "🚀", "🎉", "⚡"]


def _pick(*opts):
    return random.choice(opts)


# --------------------------- LLM path --------------------------------
def _llm_reply(chat_id: int, text: str) -> str | None:
    if not config.OPENROUTER_API_KEY:
        return None
    history = db.get_history(chat_id)[-config.MAX_HISTORY:]
    messages = [{"role": "system", "content": config.SYSTEM_PROMPT}]
    messages += history
    messages.append({"role": "user", "content": text})
    models = [config.MODEL] + config.FALLBACK_MODELS
    for model in models:
        try:
            r = requests.post(
                "https://openrouter.ai/api/v1/chat/completions",
                headers={
                    "Authorization": f"Bearer {config.OPENROUTER_API_KEY}",
                    "Content-Type": "application/json",
                    "HTTP-Referer": "https://nova-bot.local",
                    "X-Title": "Nova Bot",
                },
                json={"model": model, "messages": messages,
                      "max_tokens": 220, "temperature": 0.9},
                timeout=config.REQUEST_TIMEOUT,
            )
            if r.status_code == 200:
                data = r.json()
                return data["choices"][0]["message"]["content"].strip()
            if r.status_code == 429:
                continue  # try next model
        except Exception:
            continue
    return None


# ------------------------ Rule-based fallback ------------------------
def _rule_reply(text: str) -> str:
    t = text.lower().strip()
    if re.search(r"\b(hi|hello|hey|yo|sup|hlo|helo)\b", t):
        return (f"Hey there {_pick('friend','champ','legend','player')}! "
                f"{_pick('Ready to play?', 'Wanna earn some coins?', 'Lets level up!')} "
                f"Try /daily for a bonus or /games to start. {random.choice(_EMOJI)}")
    if re.search(r"\b(who are you|your name|what are you|about you)\b", t):
        return ("I'm Nova ⚡ — your fun companion, game master & virtual-world "
                "manager! I run economy, properties, pets, casino & events. "
                "Type /help to see everything I do.")
    if re.search(r"\b(thanks|thank you|ty|thx)\b", t):
        return _pick("Anytime! 🙌", "No prob, champ 💪", "Happy to help ✨")
    if re.search(r"\b(how|what|explain|help me)\b", t) and "command" in t or "cmd" in t:
        return ("You've got a ton of commands! 🎮 /profile, /wallet, /daily, "
                "/spin, /shop, /property, /pet, /casino, /leaderboard, /guild… "
                "Send /help for the full list.")
    if re.search(r"\b(bored|lonely|sad|tired)\b", t):
        return (_pick("Aw, let's fix that! 🎉", "Time for fun! 🚀")
                + " Spin the wheel with /spin or test your luck at /blackjack!")
    if "?" in t:
        return (_pick("Good question! 🤔", "Hmm! 🧠")
                + " I'm best at games & economy — try /games, /shop or /daily. "
                "What do you feel like doing?")
    # generic engaging nudge
    return (_pick("Nice! 😄", "Got it! 👍", "For sure! 💡")
            + f" While we chat, you're earning coins. "
            f"Peek at /profile or spin /spin for a surprise! {random.choice(_EMOJI)}")


# ----------------------------- Public --------------------------------
def nova_reply(chat_id: int, user_id: int, text: str) -> str:
    """Return a conversational reply, recording history."""
    llm = _llm_reply(chat_id, text)
    if llm:
        db.add_history(chat_id, "user", text)
        db.add_history(chat_id, "assistant", llm)
        return llm
    # rule-based
    reply = _rule_reply(text)
    db.add_history(chat_id, "user", text)
    db.add_history(chat_id, "assistant", reply)
    return reply
